/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#ede8dc",
        "background": "#fef9ed",
        "on-tertiary-fixed": "#251a00",
        "primary-fixed-dim": "#ecc155",
        "surface-dim": "#dedace",
        "surface": "#fef9ed",
        "surface-variant": "#e7e2d6",
        "inverse-primary": "#ecc155",
        "tertiary": "#775a09",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#1d1b18",
        "secondary-fixed-dim": "#cac6c1",
        "on-error-container": "#93000a",
        "primary": "#775a00",
        "on-background": "#1d1c14",
        "inverse-surface": "#323028",
        "surface-container-highest": "#e7e2d6",
        "surface-container": "#f3ede1",
        "surface-bright": "#fef9ed",
        "tertiary-container": "#b59341",
        "surface-container-low": "#f8f3e7",
        "primary-container": "#D4AF5A",
        "on-surface": "#1d1c14",
        "on-tertiary-container": "#3e2d00",
        "secondary": "#605e5a",
        "tertiary-fixed-dim": "#e8c26b",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#5b4300",
        "outline": "#7f7664",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdf9b",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#666460",
        "secondary-fixed": "#e6e2dc",
        "on-primary-fixed-variant": "#5a4400",
        "on-primary-container": "#3d2d00",
        "outline-variant": "#d1c5b0",
        "primary-fixed": "#ffdf97",
        "inverse-on-surface": "#f5f0e4",
        "surface-tint": "#775a00",
        "on-primary-fixed": "#251a00",
        "on-surface-variant": "#4e4636",
        "secondary-container": "#e6e2dc",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#484743",
        "iron-ink": "#1A1916",
        "hero-dark": "#0D0C09",
        "stone": "#4e4636"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "sm": "8px",
        "md": "12px",
        "lg": "16px",
        "xl": "20px",
        "2xl": "28px",
        "3xl": "36px",
        "full": "9999px"
      },
      spacing: {
        "stack_sm": "8px",
        "stack_md": "16px",
        "gutter": "clamp(24px, 3vw, 56px)",
        "section_v_padding": "96px",
        "stack_lg": "32px",
        "section_v_padding_mobile": "64px",
        "max_width": "100%",
        "margin_container": "auto"
      },
      fontFamily: {
        "display-lg": ["DM Serif Display"],
        "body-lg": ["IBM Plex Sans"],
        "eyebrow-mono": ["IBM Plex Mono"],
        "data-table": ["IBM Plex Mono"],
        "body-md": ["IBM Plex Sans"],
        "label-sm": ["IBM Plex Mono"],
        "headline-md": ["DM Serif Display"]
      },
      fontSize: {
        "display-lg": ["clamp(48px, 7vw, 80px)", { "lineHeight": "1.05", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-lg-mobile": ["clamp(36px, 9vw, 52px)", { "lineHeight": "1.1", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "300" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "eyebrow-mono": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "data-table": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
